### ISSUE TITLE
Running tutorial TODO list

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#138]
i''m going to stash tutorial todo's here and then individually work on them / parse them out into separate issues

- [ ] Create a graphic / HTML css interactive element for the tutorial landing page that introduces the pieces of a python package and also how these tutorials are organized ... maybe even that step box diagram?
- [ ] Consider how people might starting creating a package. would they create a repo, clone it and work from there first? or do they work on the code first and then turn it into a repo. i've actually done both.  Other times they might start by working locally and then pushing the repo content to github / gitlab. in any case the readme and license lessons may or may not be relevant. so we should have a pregame for setting up a fresh repo, creating an initial .gitignore, readme and license. and then link to the chose a license lesson.
- [ ] It might be good to have them add development requirements up front in their pyproject.toml file
